version: "3.3"
services:
  fastapi:
    container_name: web
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - 8080:8080
    entrypoint: conda run -n imaging-env uvicorn app:app --host 0.0.0.0 --port 8080 --loglevel=info

  worker:
    container_name: worker
    build:
      context: ..
      dockerfile: docker/Dockerfile
    entrypoint: conda run -n imaging-env celery worker --app=tasks.worker.celery_app -c 2 --loglevel=info
  rabbit:
    container_name: rabbit
    image: rabbitmq:latest
  # redis:
  #   container_name: redis
  #   image: redis:alpine
  #   restart: always    